"""add review

Revision ID: 9b48d31ac575
Revises: 82a1a06ec4d3
Create Date: 2024-06-29 17:23:06.182140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b48d31ac575'
down_revision = '82a1a06ec4d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
